server:
  port: ${PORT:9001}
  servlet:
    contextPath: /listenerEmail

spring:
  profiles:
    active: ${ENV:prod}
  application:
    name: limpacity
  jpa:
    open-in-view: false
    show-sql: ${LOG_SQL:true}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql: true
        dialect: org.hibernate.dialect.MySQL55Dialect
        proc:
          param_null_passing:true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      javax:
        persistence.query.timeout: ${QUERY_TIMEOUT:10000}
        persistence.lock.timeout: ${LOCK_TIMEOUT:3000}
  rabbitmq:
    host: ${RABBIT-HOST}
    port: ${RABBIT-PORT}
    username: ${RABBIT-USERNAME}
    password: ${RABBIT-PASSWORD}
    virtual-host: ${RABBIT-VHOST}
    events:
      solicitaColeta:
        exchange: ${MQ_EXCHANGE_COLETA}
        queueNotificarEmail: ${MQ_COLETA_NOTIFICAR_EMAIL}
  security:
    user:
      name: ${SECURITY-USERNAME}
      password: ${SECURITY-PASSWORD}
security:
  jwt:
    uri: "/**"
    prefix: ${JWT_PREFIX}
    secret: ${JWT_SECRET}

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}

limpacity:
  apiUrl: ${API_URL:http://localhost:9001/limpacity/api/v1/coleta}
  apiToken: ${API_TOKEN:TEST}

info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

springdoc:
  version: '@project.version@'
  api-docs:
    groups:
      enabled: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false

timezone: ${TIMEZONE:America/Sao_Paulo}